import '../models/exercises.dart';

// 'All',
// 'Back',
// 'Abs',
// 'Traps',
// 'Triceps',
// 'Forearms',
// 'Calves',
// 'Front Delts',
// 'Glutes',
// 'Chest',
// 'Biceps',
// 'Quads',
// 'Hamstrings',
// 'Side Delts',
// 'Rear Delts',

List<Exercise> DEFAULT_EXERCISES = [
  // Back
  Exercise(
    name: 'Barbell Bent Over Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cambered Bar Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Barbell Row to Chest',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Underhand EZ Bar Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Chest Supported Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Chest Supported Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'T Bar Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Dumbbell Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Two Arm Dumbbell Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Single Arm Dumbbell Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Hammer Low Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seal Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Inverted Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated Cable Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Normal Grip Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Wide Grip Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Parallel Grip Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Underhand Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Assisted Normal Grip Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
    assisted: true,
  ),
  Exercise(
    name: 'Assisted Wide Grip Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
    assisted: true,
  ),
  Exercise(
    name: 'Assisted Parallel Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
    assisted: true,
  ),
  Exercise(
    name: 'Assisted Underhand Pullup',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
    assisted: true,
  ),
  Exercise(
    name: 'Normal Grip Pulldown',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Wide Grip Pulldown',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Parallel Pulldown',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Underhand Pulldown',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Narrow Grip Pulldown',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Hammer High Row',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Pullover',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Pullover',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Straight Arm Pulldown',
    barWeight: 45,
    bodyparts: ['Back'],
    barInKG: false,
  ),
  //Ab
  Exercise(
    name: 'Hanging Knee Raise',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'Hanging Straight Leg Raise',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Crunch',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'Modified Candlestick',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'Rope Crunch',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'Slant Board Situp',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'V-Up',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  Exercise(
    name: 'Reaching Situp',
    barWeight: 45,
    bodyparts: ['Abs'],
    barInKG: false,
  ),
  //Traps
  Exercise(
    name: 'Barbell Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Barbell Bent Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Lean Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Single Arm Side Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Side Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated Dumbbell Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Bent Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Bent Shrug',
    barWeight: 45,
    bodyparts: ['Traps'],
    barInKG: false,
  ),
  //Triceps
  Exercise(
    name: 'Barbell Triceps Overhead Extensions',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Assisted Dip',
    barWeight: 45,
    bodyparts: ['Triceps', 'Chest'],
    barInKG: false,
    assisted: true,
  ),
  Exercise(
    name: 'Barbell Skullcrusher',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Overhead Triceps Extensions',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Single Arm Pushdown',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dip',
    barWeight: 45,
    bodyparts: ['Triceps', 'Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Skullcrusher',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Ez Bar Overhead Triceps Extension',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Inverted Skullcrusher',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Triceps Extension',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Triceps Pushdown',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Rope Overhead Triceps Extension',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Rope Pushdown',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated EZ Bar Overhead Triceps Extension',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'JM Press',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated Barbell Overhead Triceps Extension',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  //Forearms
  Exercise(
    name: 'Dumbbell Standing Wrist Curls',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Barbell Standing Wrist Curls',
    barWeight: 45,
    bodyparts: ['Forearms'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Bench Wrist Curls',
    barWeight: 45,
    bodyparts: ['Triceps'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Wrist Curls',
    barWeight: 45,
    bodyparts: ['Forearms'],
    barInKG: false,
  ),
  //Calves
  Exercise(
    name: 'Calf Machine',
    barWeight: 45,
    bodyparts: ['Calves'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated Calf Machine',
    barWeight: 45,
    bodyparts: ['Calves'],
    barInKG: false,
  ),
  Exercise(
    name: 'Stair Calves',
    barWeight: 45,
    bodyparts: ['Calves'],
    barInKG: false,
  ),
  Exercise(
    name: 'Single-Leg Stair Calves',
    barWeight: 45,
    bodyparts: ['Calves'],
    barInKG: false,
  ),
  Exercise(
    name: 'Deficit Smith Machine Calves',
    barWeight: 45,
    bodyparts: ['Calves'],
    barInKG: false,
  ),
  Exercise(
    name: 'Leg Press Calves',
    barWeight: 45,
    bodyparts: ['Calves'],
    barInKG: false,
  ),
  //Front Delts
  Exercise(
    name: 'Barbell Front Raise',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Underhand Front Raise',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Front Raise',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'EZ Bar Underhand Front Raise',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Shoulder Press',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated Barbell Shoulder Press',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Seated Shoulder Press',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Standing Barbell Shoulder Press',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Standing Barbell Shoulder Press',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Standing Dumbbell Shoulder Press',
    barWeight: 45,
    bodyparts: ['Front Delts'],
    barInKG: false,
  ),
  //Glutes
  Exercise(
    name: 'Barbell Hip Thrust',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Barbell Walking Lunge',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Pull-Through',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Deadlift',
    barWeight: 45,
    bodyparts: ['Glutes', 'Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Deficit Deadlift',
    barWeight: 45,
    bodyparts: ['Glutes', 'Hamstrings', 'Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Walking Lunge',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Glute Kickback',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Hip Thrust',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Reverse Lunge',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Single Leg Hip Thrust',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Split Squat',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Sumo Deadlift',
    barWeight: 45,
    bodyparts: ['Glutes', 'Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Sumo Deficit Deadlift',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Sumo Squat',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Trap Bar Deadlift',
    barWeight: 45,
    bodyparts: ['Glutes', 'Back'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Reverse Lunge',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Split Squat',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Single Leg Hip Thrust',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  Exercise(
    name: 'Wide Stance Belt Squat',
    barWeight: 45,
    bodyparts: ['Glutes'],
    barInKG: false,
  ),
  //Chest
  Exercise(
    name: 'Cable Flye',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Bent Flye',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Underhand Flye',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cambered Bar Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Deficit Pushup',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Flat Dumbbell Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Deficit Pushup',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Flat Dumbbell Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Flat Dumbbell Flye',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Machine Chest Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Barbell Press Medium Grip',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Barbell Press Wide Grip',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Barbell Press Narrow Grip',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Low Incline Dumbbell Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Chest Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Flye',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Medium Grip Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Narrow Pushup',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Narrow Grip Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Pec Deck Flye',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Pushup',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Incline Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Narrow Grip Incline Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Narrow Grip Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Wide Grip Incline Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Wide Grip Incline Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  Exercise(
    name: 'Wide Grip Bench Press',
    barWeight: 45,
    bodyparts: ['Chest'],
    barInKG: false,
  ),
  //Quads
  Exercise(
    name: 'Feet Forward Smith Squat',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Front Squat Cross Grip',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Front Squat',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Hack Squat',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'High Bar Squat',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Leg Extension',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Leg Press',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Narrow Stance Squat',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  Exercise(
    name: 'Belt Squat',
    barWeight: 45,
    bodyparts: ['Quads'],
    barInKG: false,
  ),
  //Hamstrings
  Exercise(
    name: 'Back Hyperextensions',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Stiff Legged Deadlift',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Glute Ham Raise',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Barbell Good Morning',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Safety Bar Good Morning',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Good Morning',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Lying Leg Curl',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Seated Leg Curl',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Single Leg Curl',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  Exercise(
    name: 'Stiff Legged Dead Lift',
    barWeight: 45,
    bodyparts: ['Hamstrings'],
    barInKG: false,
  ),
  //Side Delts
  Exercise(
    name: 'Barbell Upright Row',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Cross Body Lateral Raise',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Face Pull',
    barWeight: 45,
    bodyparts: ['Side Delts', 'Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Upright Row',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Lateral Raise',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Leaning Cable Lateral Raise',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Lateral Raise',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Smith Machine Upright Row',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Thumbs Down Lateral Raise',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Top Hold Lateral Raise',
    barWeight: 45,
    bodyparts: ['Side Delts'],
    barInKG: false,
  ),
  //Rear Delts
  Exercise(
    name: 'Bent Lateral Raise',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Cross Body Bent Lateral Raise',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Cable Single Arm Read Delt Raise',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Dumbbell Facepull',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Dumbbell Facepull',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Incline Dumbbell Lateral Raise',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Machine Reverse Flye',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
  Exercise(
    name: 'Barbell Facepull',
    barWeight: 45,
    bodyparts: ['Rear Delts'],
    barInKG: false,
  ),
];
